services:
    app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        image:  php:8.2-fpm-alpine
        container_name: laravel-app
        volumes:
            - ./:/var/www/html # Mount your application code
            - /var/www/html/vendor # Use a container volume for vendor files
            - /var/www/html/node_modules # Use a container volume for node_modules
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost:9000
            - LOG_CHANNEL=stack
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=sail
            - DB_PASSWORD=password

        depends_on:
            - db

    web:
        # build:
        #     context: ./
        #     dockerfile: Dockerfile
        image: nginx:latest
        container_name: webserver
        ports:
            - "9000:80"
            # - "443:443"
        volumes:
            - ./:/var/www/html:ro # Montamos el c√≥digo como solo lectura para Nginx
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: database
        ports:
            - "3311:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: sail
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data: